###############################################################################
# Options
###############################################################################


# Location of the data relative to the config
data_dir: ../data
# Location of the figures relative to the config
figure_dir: ../data/figures

# What day of the year to start on.
# Default is September 1st, start of the Northwestern Financial Year
start_of_year: September 1

# Aesthetic options
page_title: 'Outreach Data'
# Seaborn color palette to use. More options at https://seaborn.pydata.org/tutorial/color_palettes.html
color_palette: deep

###############################################################################
# Advanced Options
###############################################################################
# The below options must be modified to adapt the dashboard to your own purposes,
# but most users of the completed dashboard will not need to modify them.

# Filetree options
input_dirname: raw_data
output_dirname: processed_data
website_data_file_pattern: News_Report*.csv
press_office_data_file_pattern: press_office*.xls*
combined_filename: press.csv

# What to group by
# If you add additional categorical columns to the data, you can specify them here and they will be added to the dashboard.
groupings:
  - Research Topics
  - Press Types
  - Categories

## Column Classifications
# The anything that's in a given grouping can be analyzed similarly.
primary_id_column: Year
id_columns: # Unique identifiers
  - Grads
numerical_columns: # Numeric columns that can be summed
  - Grads
  - Postdoc
  - Faculty
  - Staff
date_columns: # Dates
  - Date
x_columns: # Data will be binned by these along the x-axis
  - Year # For example, a value of 2019 would be grouped into the 2019-2020 financial year
categorical_columns: # Categorical columns that can be grouped, e.g. all Press Types=="Science" articles
  - Research Topics
  - Press Types
  - Categories
text_columns: # Text columns that can be searched
  - Title
  - Permalink
  - Top Outlets
  - Notes

## Custom Categories
# Use boolean logic to define categories.
# In addition to boolean logic, preceeding the definition with 'only' will restrict the category to only the tags that show up in the proceeding definition.
# Any categories not defined here will be left as is if they are the sole tag, or added to an 'Other' category if they are one of multiple tags.

