###############################################################################
# Options
###############################################################################

# Location of the data relative to the config
data_dir: ../test_data

# What day of the year to start on
year_start: September 1

###############################################################################
# Advanced Options
###############################################################################

# What to group by
groupings:
  - Research Topics
  - Press Types
  - Categories

# Filetree options
input_dirname: input
output_dirname: processed
website_data_file_pattern: News_Report*.csv
press_office_data_file_pattern: press_office*.xls*
transform_nb_fp: default # Defaults to src/transform.ipynb
dashboard_nb_fp: default # Defaults to src/dashboard.ipynb