###############################################################################
# Options
###############################################################################

# What day of the year to start on
year_start: September 1

# Location of the data relative to the config
data_dir: ../data
# Location of the figures relative to the config
figure_dir: ../data/figures

# Aesthetics
color_palette: deep # Seaborn color palette to use

###############################################################################
# Advanced Options
###############################################################################

# What to group by
groupings:
  - Research Topics
  - Press Types
  - Categories

# Custom categories
new_categories:
  Research Topics:
    'Compact Objects': "'Life & Death of Stars' | 'Gravitational Waves & Multi-Messenger Astronomy' | 'Stellar Dynamics & Stellar Populations'"
  Press Types:
    'Northwestern Press (Inclusive)': "'Northwestern Press' | ( 'Northwestern Press' & 'CIERA Stories' )"
  Categories:
    'Research': "'Science' | 'Data Science & Computing'"

# Filetree options
input_dirname: raw_data
output_dirname: processed_data
website_data_file_pattern: News_Report*.csv
press_office_data_file_pattern: press_office*.xls*
combined_filename: press.csv
transform_nb_fp: default # Defaults to src/transform.ipynb
dashboard_nb_fp: default # Defaults to src/dashboard.ipynb